### ISSUE TITLE
Research Versioning for the new dmptool apps

### ISSUE THREAD

**Issue by jupiter007** [CDLUC3/dmsp_aws_prototype#155]
Some things to consider:

- Use SemVer for versioning (i.e., Major, Minor, Patch)
- Add a package/script to the apps that can be called in the pipeline to update the package.json version
- Make sure to tag the release in git
- Will want to make sure that the version update happens after all tests pass and before deployment

**Comment by jupiter007** [comment]
I'm time-boxing the research to 2-3 days. Obviously we'll have to create additional tickets to implement once the research is complete.

**Comment by bofstein** [comment]
Share to wider uc3-dev channel for feedback from other teams

**Comment by jupiter007** [comment]
There is a built-in command in node apps, `npm version <major | minor |patch>`, that updates the package.json version. It also adds the change and commits it to our local git branch and it also creates a git tag for us named after the updated version. Then we'd have to push our changes to the repo: 
`git push origin main`
`git push origin --tags`

The shell script would look something like: 
```
#!/bin/bash

# Check for the required argument
if [ -z "$1" ]; then
  echo "Usage: $0 {major|minor|patch}"
  exit 1
fi

# Bump the version using npm
npm version $1 -m "Bump version to %s"

# Push changes and tags to the repository
git push origin main
git push origin --tags
```

We can store the above script at the root of our repo and call it from the buildspec.yaml file as a "post-build" step like :   

```
post_build:
    commands:
      - echo Build completed on `date`
      - echo Bumping version...
      # Use an environment variable to specify the version bump type
      - ./bump-version.sh $VERSION_BUMP_TYPE
```
However, I'm not certain what the best way would be to set the version bump type. Would we want to configure the "version bump type" in the AWS console, or maybe using the AWS client?

**Comment by jupiter007** [comment]
Posted question about versioning in Slack's "uc3-dev" channel last week. I didn't get any responses.

Today, I brought it up in the "Dev Coffee" meeting. Still waiting to talk to Terry, Merritt Technical Lead, about it as well when he gets back from vacation.

**Comment by jupiter007** [comment]
I looked into possibly passing in the VERSION_BUMP_TYPE in the approval step of the pipeline, but apparently that happens after the post_build.

I'm hoping we can use semver versioning though, and have the app version and git tag be in sync.

For now, I'm going to close this ticket, and we'll revisit later when we get closer to MVP.

**Comment by bofstein** [comment]
For now, based on discussions with Ashley, going to combine manual process and this automated pipeline; final steps will be manual.

Need to document all the steps, do it manual for now, goals is to eventually automate it.
