### ISSUE TITLE
Add HostedZone for the prd site

### ISSUE THREAD

**Issue by briri** [CDLUC3/dmsp_aws_prototype#76]
Update the CloudFormation template that manages our stg/prd Route53 HostedZones so that we have: `dmphub.uc3prd.cdlib.net`.

@ashleygould I could not figure out which repo you use for managing this (perhaps I don't have access).

**Comment by ashleygould** [comment]
I've generated the 2 new route53 hostedzones in the cdl-uc3-prd account: [uc3prd.cdlib.org](http://uc3prd.cdlib.org/), [uc3prd.cdlib.net](http://uc3prd.cdlib.net/) .  I have requested IAS to configure zone delegation from the parent dns domains.  I'll let you know when these resolve publicly.

**Comment by briri** [comment]
HostedZone has been created and related AWS resources were created. Thanks @ashleygould
