### ISSUE TITLE
Build CodePipeline and CodeBuild for the UI

### ISSUE THREAD

**Issue by briri** [CDLUC3/dmsp_aws_prototype#81]
Build our the CF definition for a CodePipeline that watches the `dmsp_ui_prototype` repository and a CodeBuild that runs tests, builds and then deploys to CloudFront.

**Comment by briri** [comment]
Initial build and pipeline have been created. The pipeline current watches the `development` branch and will build the dmsp_ui_prototype application and auto-deploy to the S3 bucket in the `/ui` path (for now).

The new dev will need to update the `buildspec.yaml` in that project to do the build appropriately. 

Depending on timing, if we can get the landing pages rebuilt in the new UI, we can stop using the `/ui` path and instead deploy to the bucket's root. If we cannot get that done in the short term we should create a separate CloudFront distro (and S3 bucket) to host the UI.

**Comment by jupiter007** [comment]
Hi @briri , I added my codebuild and codepipeline changes directly to the ["ecs" branch](https://github.com/CDLUC3/dmsp_aws_prototype/tree/ecs) of "dmsp_aws_prototype" repo. Let me know if that's ok.

It looks like they were created, but the codepipeline had an error because I think it couldn't find the `buildspec.yaml` file in the `development` branch of `dmsp_frontend_prototype`.

**Comment by briri** [comment]
Excellent! We can touch base today to take a look at the build and see what's going on.

**Comment by jupiter007** [comment]
I set the environmental variable in the Dockerfiles in the frontend app, and that worked. I am now able to get the graphql endpoint for https://ui.dmphub.uc3dev.cdlib.net/ and we are able to see the contributor roles displaying on the page.

**Comment by briri** [comment]
Excellent!

**Comment by briri** [comment]
This is complete. We still need to setup the AWS Chatbot in CloudFormation, but I ran into a wall so opened a separate ticket to track that work #146. We can address that prior to building out our stage environment
