### ISSUE TITLE
Create Dynamo tables for typeahead entries (Orgs)

### ISSUE THREAD

**Issue by briri** [CDLUC3/dmsp_aws_prototype#85]
Determine if it's better to have a single table for all of this or smaller tables dedicated to their use

Create new DyanmoDB tables for:
- Orgs (initially fed by the ROR snapshot) - this ticket
- Repositories (initially fed by the re3Data snapshot) - moved to https://github.com/CDLUC3/dmsp_aws_prototype/issues/150
- MetadataStandards (initially  fed by the RDA and OpenAire snapshots) - moved to https://github.com/CDLUC3/dmsp_aws_prototype/issues/151

Partition keys should be the unique identifier from the source system and sort keys should be the type of record (e.g. "ORG")

**Comment by bofstein** [comment]
Decided to have a single table.  This table covers the Orgs part, while Repositories and Metadata have moved to new tickets:
https://github.com/CDLUC3/dmsp_aws_prototype/issues/150
https://github.com/CDLUC3/dmsp_aws_prototype/issues/151

**Comment by mariapraetzellis** [comment]
This is a duplicate issue with #84
